"""Commercial constants for ROAR — pricing, purchase URLs, support address, and
the bundled license-verification public key.

Pure constants only. This module imports nothing from the app's runtime and
never touches transcript/audio/history/vocabulary/clipboard/network. Editions
live in `entitlements.py` (the single source of truth for the vocabulary).

Placeholders marked `# TODO before launch` must be replaced with real values
(and IS_PRODUCTION flipped, with the real public key swapped in) before any paid
release. See docs/COMMERCIAL_READINESS_CHECKLIST.md.
"""

DEFAULT_EDITION = "core"
CURRENT_MAJOR_VERSION = 1

# ---------------------------------------------------------------------------
# CANONICAL PRICING — the single source of truth for what ROAR costs.
#
# One-time prices, USD. Buy once, use forever; no subscription.
#
# Edition IDs (the dict keys) are stable and machine-readable. A PRICE IS NEVER
# AN ENTITLEMENT IDENTIFIER — what each edition unlocks lives in entitlements.py.
#
# `purchase_url` points at ROAR's own pricing page (published from site/ by
# .github/workflows/pages.yml), never at a payment processor: the website owns
# checkout, so links can change without shipping a new app build. See
# docs/STRIPE_SETUP.md.
# ---------------------------------------------------------------------------
_SITE = "https://xhan145.github.io/roar/"

PRICING = {
    "core": {
        "display_name": "ROAR Core",
        "price_usd": 0,
        "price_label": "Free",
        "purchase_url": None,  # free: there is nothing to buy
    },
    "pro": {
        "display_name": "ROAR Pro",
        "price_usd": 19,
        "price_label": "$19 once",
        "purchase_url": _SITE + "#pricing",
    },
    "developer": {
        "display_name": "ROAR Developer",
        "price_usd": 29,
        "price_label": "$29 once",
        "purchase_url": _SITE + "#pricing",
    },
    "supporter": {
        "display_name": "ROAR Supporter",
        "price_usd": 49,
        "price_label": "$49 once",
        "purchase_url": _SITE + "#pricing",
    },
}

# The editions a customer can actually buy. `core` is deliberately absent.
PAID_EDITIONS = ("pro", "developer", "supporter")

# Derived — kept so existing consumers (upgrade_prompts.py, the settings
# bridge) need no change and cannot drift from PRICING.
PRO_PRICE_USD = PRICING["pro"]["price_usd"]
DEVELOPER_PRICE_USD = PRICING["developer"]["price_usd"]
SUPPORTER_PRICE_USD = PRICING["supporter"]["price_usd"]

PURCHASE_URL_PRO = PRICING["pro"]["purchase_url"]
PURCHASE_URL_DEVELOPER = PRICING["developer"]["purchase_url"]
PURCHASE_URL_SUPPORTER = PRICING["supporter"]["purchase_url"]

# Published support / pre-order mailbox. Buyers reach this from the pricing page
# and the in-app License screen; it's where manual license fulfilment happens.
SUPPORT_EMAIL = "gregm@joincollective.net"

# When False (repo/dev builds), dev-signed licenses are accepted so the app can
# be exercised end-to-end. A production build sets this True AND uses the real
# public key below; then dev-signed licenses (env:"dev") are rejected. See
# license.py.
IS_PRODUCTION = True

# PRODUCTION license-verification public key (Ed25519), generated by
# scripts/generate_keypair.py. The matching PRIVATE key is NEVER committed — it
# lives only in the owner's ~/.roar-signing/ and is used by
# scripts/issue_license.py to sign real customer licenses. Rotating this key
# invalidates every license already sold, so treat it as permanent.
LICENSE_PUBLIC_KEY_PEM = """\
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA8omc9mYaE/oDRg67VA8BgY5uP2T/CCgnHcf1BNBMF2c=
-----END PUBLIC KEY-----
"""

# SUBORDINATE fulfilment key: its private half lives ONLY in the Vercel
# fulfilment service's env (never on this machine's disk outside
# ~/.roar-signing/, never in the repo). REVOCATION: deleting it from the
# LICENSE_PUBLIC_KEYS tuple alone is NOT enough — license._default_verifier
# reads FULFILLMENT_PUBLIC_KEY_PEM directly, so remove/blank THIS constant
# (a guard test pins the two lists to the same keys). Then cut a release and
# reissue affected licenses from the founder key — founder-signed licenses
# are unaffected. See docs/VERCEL_FULFILLMENT.md.
FULFILLMENT_PUBLIC_KEY_PEM = """\
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA5V8lZZEUi5X19S9OpbrrVZju5hNcrqyAFaf+zQbjxcM=
-----END PUBLIC KEY-----
"""

# Every key the app trusts, founder first. license.MultiKeyVerifier accepts a
# signature from ANY of these.
LICENSE_PUBLIC_KEYS = (LICENSE_PUBLIC_KEY_PEM, FULFILLMENT_PUBLIC_KEY_PEM)
