"""Windows version resource for ROAR.exe, generated at build time.

WHY THIS EXISTS: without a VS_VERSIONINFO block Windows Installer treats the
exe as an *unversioned* file, and applies its "don't clobber a file the user
may have changed" rule instead of a version comparison. On an in-place upgrade
that can leave the OLD binary on disk while msiexec still reports success —
observed on the 0.34.0 -> 0.35.0 upgrade, where three installs returned exit
code 0 and changed nothing. A real version resource makes the comparison
deterministic (higher version wins) and gives users a Properties -> Details
version to quote in a bug report.

Build-time only: roar.spec calls write_version_file() and hands the path to
EXE(version=...). Nothing here is imported by the running app.
"""
from __future__ import annotations

import pathlib
import re

COMPANY_NAME = "xhan145"
PRODUCT_NAME = "ROAR"
FILE_DESCRIPTION = "ROAR - local voice-to-text dictation"
ORIGINAL_FILENAME = "ROAR.exe"

_LEADING_INT = re.compile(r"\d+")


def version_tuple(version):
    """"0.35.0" -> (0, 35, 0, 0) — the 4-part form the resource requires.

    Tolerant on purpose: a release build must not die on a version string like
    "0.35.0rc1". Missing or non-numeric parts become 0.
    """
    parts = str(version).strip().split(".")[:4]
    nums = []
    for part in parts:
        m = _LEADING_INT.match(part.strip())
        nums.append(int(m.group()) if m else 0)
    nums += [0] * (4 - len(nums))
    return tuple(nums)


def version_info_text(version):
    """Render the PyInstaller version-resource file for `version`."""
    vt = version_tuple(version)
    dotted = ".".join(str(n) for n in vt)
    display = str(version).strip() or dotted
    return f'''# Generated by scripts/version_info.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        "040904B0",
        [
          StringStruct("CompanyName", "{COMPANY_NAME}"),
          StringStruct("FileDescription", "{FILE_DESCRIPTION}"),
          StringStruct("FileVersion", "{dotted}"),
          StringStruct("InternalName", "{PRODUCT_NAME}"),
          StringStruct("OriginalFilename", "{ORIGINAL_FILENAME}"),
          StringStruct("ProductName", "{PRODUCT_NAME}"),
          StringStruct("ProductVersion", "{display}"),
        ],
      )
    ]),
    VarFileInfo([VarStruct("Translation", [0x0409, 1200])]),
  ],
)
'''


def write_version_file(version, path="build/version_info.txt"):
    """Write the resource file for `version` and return its path."""
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(version_info_text(version), encoding="utf-8")
    return str(p)
